### ISSUE TITLE
Autoformatting breaks highlights

### ISSUE THREAD

**Issue by mrdgo** [p00f/nvim-ts-rainbow#143] opened 2022-10-24 06:50 UTC
I use `jdtls` and autocmds to format on save. When I save a file like this:
![image](https://user-images.githubusercontent.com/1636639/197464249-609252b2-208e-4b3c-a4a7-58dce54c4a50.png)

after saving and formatting, the highlights look like this:
![image](https://user-images.githubusercontent.com/1636639/197464293-adf5e6fc-39f9-4493-ac55-9d280e3d1176.png)

As you can see, the third `@` is highlighted just as the closing `}` was. In this example, it is not a huge problem, but in larger files, it tends to mess up a lot more.

Do I need to manually hook something to the formatting? This bugs me a bit tbh

**Comment by p00f** [comment] 2022-10-24 07:31
Duplicate of #112

**Comment by p00f** [comment] 2022-10-24 07:32
Status: No idea how to fix this, help wanted

**Closed by p00f** 2022-10-24 07:32 UTC
