### ISSUE TITLE
throw error when editing rust file

### ISSUE THREAD

**Issue by alan-w-255** [p00f/nvim-ts-rainbow#3] opened 2020-11-29 14:02 UTC
when i enable this plugin, then edit the rust file. nvim throw error:

`Error executing lua callback: /usr/local/share/nvim/runtime/lua/vim/treesitter/query.lua:272: invalid start`

I am using:
NVIM v0.5.0-888-g8b2887bd5
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

**Comment by p00f** [comment] 2020-11-29 14:03
yeah there's something wrogn with css too

**Comment by p00f** [comment] 2020-11-29 14:06
can you share the file you're editing and reproduction steps? (like what exactly you did and the line and col numbers of that position)

**Comment by alan-w-255** [comment] 2020-11-29 14:15
```rust
fn main() {
    let a_rename="hi";
    println!("{}", a_rename);
}

#[test]
fn it_work() {
    assert!(1+1 == 2);
}
```

I put the cursor on the `println`, then press `o` to start a newline, then nvim throw the error.

**Comment by p00f** [comment] 2020-11-29 14:28
In https://github.com/nvim-treesitter/nvim-treesitter/issues/528 vigoux said this is an upstream issue.

Can you confirm this is the case here too @vigoux?

**Comment by p00f** [comment] 2020-11-29 14:32
point to be noted is that this doesn't happen when the rainbow module is disabled

**Comment by alan-w-255** [comment] 2020-11-29 14:50
Yes, it won't happen when i disable 'rust' filetype in rainbow config.

It seem the following code will cause the errors:

```rust
#[test]
fn it_work() {
    assert!(1+1 == 2);
}
```
when i delete those code, there is no more error. but there is no rainbow brackets neither

**Comment by p00f** [comment] 2020-11-29 17:09
my `~/.local/share/nvim/log` says something like
> RPC: ensure that it is properly synced

but i deleted my log file by mistake

can you show what it says @alan-w-255 ?

**Comment by alan-w-255** [comment] 2020-11-30 04:38
[log.txt](https://github.com/p00f/nvim-ts-rainbow/files/5613834/log.txt)
@p00f

**Comment by p00f** [comment] 2020-11-30 05:17
can you try the error-handling branch (with some more editing/testing)?

**Comment by alan-w-255** [comment] 2020-11-30 06:56
I have test the `error-handing branch`,  there is no more errors. It is fixed.

**Comment by p00f** [comment] 2020-11-30 06:58
I'll merge the branch soon then.

I'll keep this issue open as a reminder to keep checking if the underlying problem is fixed

**Comment by p00f** [comment] 2020-11-30 08:13
I've merged the branch

**Comment by p00f** [comment] 2021-01-20 23:21
I just closed #1 because it seems fixed, maybe it is indeed fixed upstream - @vigoux ?

**Comment by p00f** [comment] 2021-01-24 16:51
Closing because this is not reproducible anymore

**Closed by p00f** 2021-01-24 16:51 UTC
Labels: upstream
