### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by xaljer** [p00f/nvim-ts-rainbow#5] opened 2020-12-06 16:26 UTC
When I enable this plugin and type words, coc's auto completion become very slow and broken. After this, cursor moving also get lag. When I disable it, every thing works well.

**Comment by p00f** [comment] 2020-12-06 17:13
Ik, there are performance issues. I'm not experienced enough to fix them

**Comment by xaljer** [comment] 2020-12-19 17:09
I test on latest coc.nvim, neovim and ts-rainbow, this issue still exist.

**Comment by p00f** [comment] 2020-12-20 04:54
I tested this properly, the slowdown is only when completion is enabled. I should've tested this the first time oof

**Comment by xaljer** [comment] 2020-12-27 06:53
It looks like still slowdown many operations like move or edit in my environment.

**Comment by fgheng** [comment] 2020-12-31 03:11
The same problems occurred while I  edit a python file, but other file is ok.

**Comment by tramhao** [comment] 2021-01-14 18:42
for me, the slow down happens in lua file. I found in lsp.log
```
pack/packer/opt/nvim-lspconfig/lua/lspconfig/configs.lua:57 ]     "        The language server sumneko_lua
incorrectly triggers a registerCapability handler\n        despite dynamicRegistration set to false. Please report upstream.\n
```

don't know if it's relevant. I'm using nvim-lspconfig, treesitter, completion-nvim and ts-rainbow.

**Comment by p00f** [comment] 2021-01-14 19:03
i don't think it is relevant

**Comment by p00f** [comment] 2021-01-21 07:26
Guys it should be much better now, please update and test

**Comment by p00f** [comment] 2021-01-27 23:21
watch https://github.com/nvim-treesitter/nvim-treesitter/pull/879

**Comment by rodamaral** [comment] 2021-02-14 05:18
This is still an issue. An example that makes it noticeable is editing this [file](https://gist.github.com/rodamaral/8e33e9abe1c2d43b96b1bd7f0eab6614) with and without this plugin, specially in insert mode.

**Comment by p00f** [comment] 2021-02-14 07:39
> (not completely fixed)

**Comment by p00f** [comment] 2021-02-14 07:39
Yes I'm aware

**Comment by p00f** [comment] 2021-02-14 07:49
Unfortunately currently I have no clue how to fix this

**Comment by runiq** [comment] 2021-02-14 10:34
> This is still an issue. An example that makes it noticeable is editing this [file](https://gist.github.com/rodamaral/8e33e9abe1c2d43b96b1bd7f0eab6614) with and without this plugin, specially in insert mode.

That's quite a pathological example, don't you think…?

**Comment by p00f** [comment] 2021-02-14 11:50
1800 pairs

**Comment by rodamaral** [comment] 2021-02-14 17:17
> > This is still an issue. An example that makes it noticeable is editing this [file](https://gist.github.com/rodamaral/8e33e9abe1c2d43b96b1bd7f0eab6614) with and without this plugin, specially in insert mode.
> 
> That's quite a pathological example, don't you think…?

Yes, just to make the issue clear. Sometimes the CPU usage stays at 100% for several seconds.
But the issue exists in normal files, but the effects appear randomly at least to me.

**Comment by matu3ba** [comment] 2021-02-18 10:52
I do expierence the issue on a almost pure lua setup (using clangd) on editing a 500 LOC c++ file.
This happens on editing comments or code without typing any brackets. Probably some indexing with updates on a bracket insertion could fix this.

@p00f Can you recommend a luajit profiler to identify the source? C++ is painful without colored brackets.

**Comment by p00f** [comment] 2021-02-18 10:55
@clason does know one

**Comment by p00f** [comment] 2021-02-18 11:00
I don't have time rn, I'll look into this after a week or so

**Comment by p00f** [comment] 2021-02-18 11:08
https://github.com/p00f/nvim-ts-rainbow/blob/3557b7baa9e773fff378235851cb3caac96fd4b9/lua/rainbow/internal.lua#L92

Currently it happens on every change

**Comment by matu3ba** [comment] 2021-02-18 20:08
@p00f 

The solution should distinguish between modes: In insertion mode one wants to redraw, if any bracket was inserted.
In all other modes the solution is fine, because it should immediately redraw bracket colors.

If that wont be enough , we could also make it faster coloring by indexing and reverse iterating scopes to find what parts to redraw. But that would be notable complexity.

**Comment by p00f** [comment] 2021-02-18 21:44
idk how slow that is, `vim.api.nvim_get_mode()` returns the mode

**Comment by p00f** [comment] 2021-02-19 19:51
![image](https://user-images.githubusercontent.com/36493671/108554293-e2b7b900-7319-11eb-9a4e-8e0d7354d999.png)
`color_no` takes up 43%, maybe we can store nodewise numbers in a table?

**Comment by p00f** [comment] 2021-02-19 19:59
It's still very slow after skipping that function and just using one, next offender is `vim.highlight.range()`
![image](https://user-images.githubusercontent.com/36493671/108555100-09c2ba80-731b-11eb-8f42-4bd074fa476b.png)

**Comment by p00f** [comment] 2021-02-19 20:22
![image](https://user-images.githubusercontent.com/36493671/108557184-35936f80-731e-11eb-9cbc-f0d36b5c4e46.png)
oh my god

**Comment by xaljer** [comment] 2021-02-20 16:55
@p00f What's the tool showing in picture?

**Comment by p00f** [comment] 2021-02-20 17:07
> @p00f What's the tool showing in picture?

https://github.com/charlesmallah/lua-profiler

**Comment by cbows** [comment] 2021-02-23 14:27
I am having a similar issue when I use this plugin in combination with dense-analysis/ale  . When this plugin is enabled, ALEFix becomes very slow (several seconds).

**Comment by p00f** [comment] 2021-02-23 14:54
download `src/profiler.lua` from the repo, place it in `lua/` in the plugin directory, wrap the code you want to profile as shown in the readme, then try whatever you were doing to reproduce the bug

**Comment by cbows** [comment] 2021-02-23 16:31
I have the following

```python
def fun(
    foo: Foo = Depends(dependency.foo_dependency),
    bar: Bar = Depends(dependency.bar_dependency) # <-- trailing comma missing
) -> List[Baz]:
    ...
```

Calling `:ALEFix` will run a formatting tool (`black` in my case) that will try to add the comma. But this takes very long when ts-rainbow is enabled.

```log
 profiler.log                                                                                                                                                                                    b 
  > Total time: 0.318766 s                                                                                                                                                                            
  --------------------------------------------------------------------------------------                                                                                                              
  | FILE                : FUNCTION                    : LINE   : TIME   : %     : #    |                                                                                                              
  --------------------------------------------------------------------------------------                                                                                                              
  | ...im/plugged/nvim-t: get_capture_matches         :   169  : 0.3061 : 96.0  :    1 |                                                                                                              
  | ...im/plugged/nvim-t: (for generator)             :   131  : 0.1738 : 54.5  : 1804 |                                                                                                              
  | ...im/plugged/nvim-t: get_at_path                 :   113  : 0.1258 : 39.5  : 1803 |                                                                                                              
  | vim/shared          : split                       :   110  : 0.1011 : 31.7  : 1803 |                                                                                                              
  | .../nightly/share/nv: match_preds                 :   287  : 0.0803 : 25.2  : 4730 |                                                                                                              
  | vim/shared          : gsplit                      :    63  : 0.0615 : 19.3  : 1803 |                                                                                                              
  | vim/shared          : validate                    :   544  : 0.0536 : 16.8  : 1803 |                                                                                                              
  | vim/shared          : is_valid                    :   502  : 0.0475 : 14.9  : 1803 |                                                                                                              
  | ...im/plugged/nvim-t: split                       :   106  : 0.0175 : 5.5   : 1803 |                                                                                                              
  | vim/shared          : _is_type                    :   498  : 0.0119 : 3.7   : 5409 |                                                                                                              
  | .../nightly/share/nv: is_directive                :   283  : 0.0107 : 3.4   : 3403 |                                                                                                              
  | vim/shared          : (for generator)             :    69  : 0.0093 : 2.9   : 1803 |                                                                                                              
  | .../nightly/share/nv: apply_directives            :   326  : 0.0075 : 2.3   : 1803 |                                                                                                              
  | .../nightly/share/nv: xor                         :   279  : 0.0053 : 1.7   : 3165 |                                                                                                              
  | ...im/plugged/nvim-t: insert_to_path              :   115  : 0.0041 : 1.3   : 1803 |                                                                                                              
  | .../neovim/nightly/s: range                       :    28  : 0.0035 : 1.1   :  242 |                                                                                                              
  | vim/shared          : (for generator)             :    81  : 0.0026 : 0.8   : 5409 |                                                                                                              
  --------------------------------------------------------------------------------------
```

It happens for all other fixes as well (like adding spaces around `a=3`).

**Comment by p00f** [comment] 2021-02-23 17:09
again, `get_capture_mathces` is the most expensive function

**Comment by p00f** [comment] 2021-03-12 18:14
@matu3ba do you have any idea as to how to detect whether a bracket was inserted?

**Comment by matu3ba** [comment] 2021-03-12 22:32
@p00f I am asking TJ and the gitter chat. There is no help page on `keypress`, so I am abit clueless where to look. A user called duck suggested to use getline('.')[col('.')-1], but this is very slow.

**Comment by p00f** [comment] 2021-03-13 06:04
I can try writing queries for just brackets and use `query:iter_captures()` directly

**Comment by p00f** [comment] 2021-03-13 16:41
Can you guys try out the `query_iter_captures` branch?

**Comment by p00f** [comment] 2021-03-14 03:46
@rodamaral i tested your `test.tsx` again, it is much more usable now on the `query_iter_captures` branch

**Comment by ttys3** [comment] 2021-03-15 07:21
https://github.com/neovim/neovim/issues/14037#issuecomment-799177739

**Comment by p00f** [comment] 2021-03-15 07:25
> @mjlbach got nvim-treesitter removed and problem still exists

This plugin won't work at all without nvim-treesitter though
https://github.com/p00f/nvim-ts-rainbow/blob/35e971a5f76d12afa6804937914e78bcc040fa27/lua/rainbow.lua#L2
https://github.com/p00f/nvim-ts-rainbow/blob/35e971a5f76d12afa6804937914e78bcc040fa27/lua/rainbow.lua#L1
https://github.com/p00f/nvim-ts-rainbow/blob/35e971a5f76d12afa6804937914e78bcc040fa27/lua/rainbow/internal.lua#L1

**Comment by mjlbach** [comment] 2021-03-15 07:28
> (sorry for the tag mjlbach, I edited it)

Not quickly enough ❤️

**Comment by mjlbach** [comment] 2021-03-15 07:29
Just for the record I did not suggest removing tree-sitter lol

**Comment by ttys3** [comment] 2021-03-15 07:31
@p00f that comment is not accurate. please check the last two comments

**Comment by ttys3** [comment] 2021-03-15 07:32
@p00f  `got nvim-treesitter removed and problem still exists.` it is ref to:
if I `got nvim-treesitter removed`, the problem `CPU goes 100%` still exists.

but the CPU will goes down very qucikly.

**Comment by matu3ba** [comment] 2021-03-15 08:52
@p00f If I use packer.nvim with
```lua
  use { 'p00f/nvim-ts-rainbow', branch = 'query_iter_captures' } --TODO performance problem --
```
I cant get my c++ file colorized to investigate.

However, it works with the master branch.
treesitter config:
```lua
require'nvim-treesitter.configs'.setup {
  ensure_installed = "maintained",
  highlight = {
    enable = true,
  },
  rainbow = {
    enable = true,
  },
}
```

What am I missing?

**Comment by p00f** [comment] 2021-03-15 11:39
oh yeah i forgot to tell you, you have to write queries for each filetype. Just save `[ "{" "}" "[" "]" "(" ")"] @paren` into `<plugin-directory>/queries/cpp/parens.scm`

**Comment by p00f** [comment] 2021-03-15 11:40
nvm i did that since it had to be done anyway, please update and try

**Comment by matu3ba** [comment] 2021-03-15 19:17
@p00f It has much better performance, which is sufficient for 1k LOC and 110 brackets.
`grep -o '{' FILE | wc -l` and `find FILE -type f -exec wc -l {} + | sort -rn`.

The delay difference with and without rainbow is still noticable with and without rainbow, but the file size/number of brackets has not a noticable effect anymore. 
If one does not type very fast, it is fine to use.

**Comment by mjlbach** [comment] 2021-03-15 19:21
There have been no lsp regressions. If anything, it should be faster now.

**Comment by p00f** [comment] 2021-03-16 02:03
Great, I'll merge the new branch after writing queries for all languages :smile: . I'll still keep this open

**Comment by p00f** [comment] 2021-03-16 06:02
merged #11

**Comment by rodamaral** [comment] 2021-03-16 12:47
Performance is much better now, even in my previous file. Thanks for the efforts!

**Comment by TornaxO7** [comment] 2021-04-08 21:20
I'm using nvim-compe and it's lagging for me. If I set `rainbow = {enable=false}` than all laggs disappeared.

**Comment by matu3ba** [comment] 2021-04-08 22:35
@TornaxO7 What is the size of the file? You can run my command for all bracket types:
`grep -o '{' FILE | wc -l` on the biggest file in your project `find FILE -type f -exec wc -l {} + | sort -rn`.

Are you on latest master neovim with updated treesitter? There were breaking changes in treesitter, which may not have stabilized.

Does `:checkhealth` for your language say that everything is fine?

**Comment by TornaxO7** [comment] 2021-04-08 22:50
> Does :checkhealth for your language say that everything is fine? Your grammar might be not updated or bad.

Currently I'm coding in C and this is in `:checkhealth`:
```log
  - c              ✓ ✓ ✓ ✓ 
```
```bash
grep -o '{' FILE | wc -l
```
Output:
```
41
```

```bash
find FILE -type f -exec wc -l {} + | sort -rn.
```
output:
```
610 main.c
```

My plugins should be up to date. I executed `:PlugUpdate` but I'm still getting this performance issue when setting rainbow.enable = true.

**Comment by TornaxO7** [comment] 2021-04-08 23:04
Here's a little live demo:

https://user-images.githubusercontent.com/50843046/114106640-814ea800-98cf-11eb-8185-dc3aa105e083.mp4

**Comment by p00f** [comment] 2021-05-24 01:11
Please update and test, imo this can be closed

**Comment by p00f** [comment] 2021-05-25 09:45
@Gelio @rmagatti i take the reactions to mean this has improved?

**Comment by Gelio** [comment] 2021-05-25 10:22
> @Gelio @rmagatti i take the reactions to mean this has improved?

From my perspective, yes! I no longer have input lags when working on a ~1k LOC file. I haven't tested it extensively, but IMO looks good now

**Comment by TornaxO7** [comment] 2021-05-25 23:09
For me, it's faster now as well! Thank you for the fix :)

**Comment by p00f** [comment] 2021-05-25 23:11
Nice! Thanks to theHamsta and tzachar

**Closed by p00f** 2021-05-25 23:11 UTC
Labels: bug
